default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8
        stages:
          - commit
          - push
        args:
          - --max-line-length=120
          - --diff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
  - repo: https://github.com/psf/black
    rev: master
    hooks:
      - id: black
        name: black
        entry: black
        require_serial: true
        types: [python]
